export const ShoppingData = [
	// Fruits
	{ category: "Fruits", price: "$1", stocked: true, name: "Apple" },
	{ category: "Fruits", price: "$1", stocked: true, name: "Dragonfruit" },
	{ category: "Fruits", price: "$2", stocked: false, name: "Passionfruit" },
	{ category: "Fruits", price: "$1", stocked: true, name: "Banana" },
	{ category: "Fruits", price: "$3", stocked: true, name: "Mango" },
	{ category: "Fruits", price: "$2", stocked: true, name: "Blueberries" },
	{ category: "Fruits", price: "$4", stocked: false, name: "Strawberries" },
	{ category: "Fruits", price: "$1", stocked: true, name: "Orange" },
	{ category: "Fruits", price: "$2", stocked: true, name: "Grapes" },
	{ category: "Fruits", price: "$3", stocked: false, name: "Pineapple" },
	{ category: "Fruits", price: "$2", stocked: true, name: "Peach" },
	{ category: "Fruits", price: "$1", stocked: true, name: "Kiwi" },
	{ category: "Fruits", price: "$2", stocked: true, name: "Pear" },
	{ category: "Fruits", price: "$5", stocked: false, name: "Cherries" },
	{ category: "Fruits", price: "$1", stocked: true, name: "Lemon" },
	{ category: "Fruits", price: "$3", stocked: true, name: "Watermelon" },
	{ category: "Fruits", price: "$2", stocked: true, name: "Raspberries" },
	{ category: "Fruits", price: "$2", stocked: false, name: "Plum" },
	{ category: "Fruits", price: "$1", stocked: true, name: "Lime" },
	{ category: "Fruits", price: "$4", stocked: true, name: "Pomegranate" },
	{ category: "Fruits", price: "$2", stocked: true, name: "Apricot" },
	{ category: "Fruits", price: "$3", stocked: true, name: "Cantaloupe" },
	{ category: "Fruits", price: "$2", stocked: false, name: "Blackberries" },
	{ category: "Fruits", price: "$1", stocked: true, name: "Grapefruit" },
	{ category: "Fruits", price: "$4", stocked: true, name: "Papaya" },
	{ category: "Fruits", price: "$2", stocked: true, name: "Nectarine" },
	{ category: "Fruits", price: "$1", stocked: true, name: "Clementine" },
	{ category: "Fruits", price: "$2", stocked: false, name: "Fig" },
	{ category: "Fruits", price: "$3", stocked: true, name: "Coconut" },
	{ category: "Fruits", price: "$2", stocked: true, name: "Guava" },

	// Vegetables
	{ category: "Vegetables", price: "$2", stocked: true, name: "Spinach" },
	{ category: "Vegetables", price: "$4", stocked: false, name: "Pumpkin" },
	{ category: "Vegetables", price: "$1", stocked: true, name: "Peas" },
	{ category: "Vegetables", price: "$1", stocked: true, name: "Carrot" },
	{ category: "Vegetables", price: "$2", stocked: true, name: "Broccoli" },
	{ category: "Vegetables", price: "$1", stocked: false, name: "Lettuce" },
	{ category: "Vegetables", price: "$3", stocked: true, name: "Bell Pepper" },
	{ category: "Vegetables", price: "$1", stocked: true, name: "Onion" },
	{ category: "Vegetables", price: "$2", stocked: true, name: "Potato" },
	{ category: "Vegetables", price: "$3", stocked: false, name: "Asparagus" },
	{ category: "Vegetables", price: "$2", stocked: true, name: "Cucumber" },
	{ category: "Vegetables", price: "$1", stocked: true, name: "Garlic" },
	{ category: "Vegetables", price: "$3", stocked: true, name: "Eggplant" },
	{ category: "Vegetables", price: "$2", stocked: false, name: "Zucchini" },
	{ category: "Vegetables", price: "$1", stocked: true, name: "Corn" },
	{ category: "Vegetables", price: "$2", stocked: true, name: "Celery" },
	{ category: "Vegetables", price: "$4", stocked: true, name: "Mushroom" },
	{ category: "Vegetables", price: "$2", stocked: false, name: "Kale" },
	{ category: "Vegetables", price: "$3", stocked: true, name: "Cauliflower" },
	{ category: "Vegetables", price: "$1", stocked: true, name: "Radish" },
	{ category: "Vegetables", price: "$2", stocked: true, name: "Green Beans" },
	{ category: "Vegetables", price: "$2", stocked: true, name: "Sweet Potato" },
	{ category: "Vegetables", price: "$1", stocked: false, name: "Cabbage" },
	{ category: "Vegetables", price: "$3", stocked: true, name: "Artichoke" },
	{ category: "Vegetables", price: "$2", stocked: true, name: "Beetroot" },
	{ category: "Vegetables", price: "$1", stocked: true, name: "Brussels Sprouts" },
	{ category: "Vegetables", price: "$2", stocked: true, name: "Okra" },
	{ category: "Vegetables", price: "$3", stocked: false, name: "Leek" },
	{ category: "Vegetables", price: "$1", stocked: true, name: "Ginger" },
	{ category: "Vegetables", price: "$2", stocked: true, name: "Chard" },
];
